### PR TITLE
[#46] Replace stock buttons with regular buttons

### PR DESCRIPTION
**Pull request by jtojnar**
Closes: #46

### CODE REVIEW

**Comment by elbenfreund** [comment]
My understanding of  #46 is that "the right way" (tm) to deal with former stock buttons is not quite clear. Did you find any documentation/source that elaborates on what GTKs new best practice is?
Maybe its worth asking the gnome list...

**Comment by jtojnar** [comment]
The [documentation](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-OK:CAPS) says we should just use plain label. ebassi explains it in a StackOverflow [answer](http://stackoverflow.com/a/30986414/160386).

**Comment by elbenfreund** [comment]
I knew about the passage in the documentation and I agree that the link indicates that one should use just a labeled button but to me it was not utterly clear if there are drop in replacements for the old stock buttons to be used instead (that would be label only) or if the conveyed meaning is: "just use plain label buttons".

Here is further feedback from ``#gnome-hackers``:
> (13:25:25) zeenix: "gtk_button_new_from_stock has been deprecated since version 3.10 and should not be used in newly-written code.
> (13:25:25) zeenix: Use gtk_button_new_with_label() instead."

Thanks for taking on this issue. I will start the review right away.

**Comment by jtojnar** [comment]
I like using a proper constructor better. `new_*` functions are used in C because it lacks proper classes.

**Pull request merged**
